import React, { useState, useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Search, Edit, Eye, AlertTriangle, Sparkles } from 'lucide-react';
import { useAllSEOPages } from '@/hooks/useSEOData';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { getRegisteredRoutes } from '@/utils/routeRegistryData';
import { RouteStatusBadge } from './RouteStatusBadge';
import { SyncRoutesButton } from './SyncRoutesButton';
import { Badge } from '@/components/ui/badge';

interface EnhancedSEOPageListProps {
  onEditPage: (path: string) => void;
}

type RouteStatus = 'optimized' | 'auto-generated' | 'no-data';

interface RouteWithStatus {
  path: string;
  category: string;
  priority: number;
  status: RouteStatus;
  source: 'database' | 'fallback';
  title?: string;
  hasWarnings: boolean;
  isIndexable: boolean;
}

export const EnhancedSEOPageList: React.FC<EnhancedSEOPageListProps> = ({ onEditPage }) => {
  const { data: pages, isLoading } = useAllSEOPages();
  const [searchTerm, setSearchTerm] = useState('');
  const [categoryFilter, setCategoryFilter] = useState<string>('all');
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [languageFilter, setLanguageFilter] = useState<string>('all');

  // Combinar rutas registradas con datos SEO
  const routesWithStatus: RouteWithStatus[] = useMemo(() => {
    if (!pages) return [];

    const allRoutes = getRegisteredRoutes();
    const seoMap = new Map(pages.map(p => [p.path, p]));

    return allRoutes
      .filter(r => r.isIndexable) // Solo mostrar rutas indexables
      .map(route => {
        const seoData = seoMap.get(route.path);
        
        let status: RouteStatus;
        if (seoData?.source === 'database') {
          status = 'optimized';
        } else if (seoData?.source === 'fallback') {
          status = 'auto-generated';
        } else {
          status = 'no-data';
        }

        return {
          path: route.path,
          category: route.category,
          priority: route.priority,
          status,
          source: seoData?.source || 'fallback',
          title: seoData?.data.title,
          hasWarnings: seoData?.hasWarnings || false,
          isIndexable: route.isIndexable
        };
      });
  }, [pages]);

  const filteredRoutes = useMemo(() => {
    return routesWithStatus.filter(route => {
      const matchesSearch = 
        route.path.toLowerCase().includes(searchTerm.toLowerCase()) ||
        (route.title?.toLowerCase().includes(searchTerm.toLowerCase()) ?? false);
      
      const matchesCategory = categoryFilter === 'all' || route.category === categoryFilter;
      const matchesStatus = statusFilter === 'all' || route.status === statusFilter;
      const matchesLanguage = languageFilter === 'all' || 
        (languageFilter === 'es-ES' && route.path.startsWith('/es')) ||
        (languageFilter === 'en-US' && route.path.startsWith('/en'));

      return matchesSearch && matchesCategory && matchesStatus && matchesLanguage;
    });
  }, [routesWithStatus, searchTerm, categoryFilter, statusFilter, languageFilter]);

  if (isLoading) {
    return <div className="text-muted-foreground">Cargando rutas...</div>;
  }

  const stats = {
    total: routesWithStatus.length,
    optimized: routesWithStatus.filter(r => r.status === 'optimized').length,
    autoGenerated: routesWithStatus.filter(r => r.status === 'auto-generated').length,
    noData: routesWithStatus.filter(r => r.status === 'no-data').length
  };

  return (
    <Card className="h-[700px] flex flex-col">
      <CardHeader>
        <div className="flex items-center justify-between mb-4">
          <CardTitle>Todas las Rutas ({filteredRoutes.length})</CardTitle>
          <SyncRoutesButton onEditPage={onEditPage} />
        </div>

        {/* Stats Bar */}
        <div className="flex gap-2 mb-4 flex-wrap">
          <Badge variant="outline" className="bg-green-50 border-green-200">
            <span className="font-semibold mr-1">{stats.optimized}</span> Optimizadas
          </Badge>
          <Badge variant="outline" className="bg-blue-50 border-blue-200">
            <span className="font-semibold mr-1">{stats.autoGenerated}</span> Auto-generadas
          </Badge>
          <Badge variant="outline" className="bg-orange-50 border-orange-200">
            <span className="font-semibold mr-1">{stats.noData}</span> Sin datos
          </Badge>
        </div>

        {/* Filtros */}
        <div className="flex gap-4 flex-wrap">
          <div className="relative flex-1 min-w-[200px]">
            <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Buscar por path o título..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-9"
            />
          </div>
          <Select value={categoryFilter} onValueChange={setCategoryFilter}>
            <SelectTrigger className="w-[160px]">
              <SelectValue placeholder="Categoría" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Todas</SelectItem>
              <SelectItem value="main">Principal</SelectItem>
              <SelectItem value="service">Servicios</SelectItem>
              <SelectItem value="solution">Soluciones</SelectItem>
              <SelectItem value="blog">Blog</SelectItem>
              <SelectItem value="case-study">Casos</SelectItem>
              <SelectItem value="kit-digital">Kit Digital</SelectItem>
              <SelectItem value="tool">Herramientas</SelectItem>
            </SelectContent>
          </Select>
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-[160px]">
              <SelectValue placeholder="Estado" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Todos</SelectItem>
              <SelectItem value="optimized">Optimizadas</SelectItem>
              <SelectItem value="auto-generated">Auto-generadas</SelectItem>
              <SelectItem value="no-data">Sin datos</SelectItem>
            </SelectContent>
          </Select>
          <Select value={languageFilter} onValueChange={setLanguageFilter}>
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder="Idioma" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Todos los idiomas</SelectItem>
              <SelectItem value="es-ES">🇪🇸 Español</SelectItem>
              <SelectItem value="en-US">🇬🇧 English</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </CardHeader>
      
      <CardContent className="flex-1 overflow-y-auto">
        <div className="space-y-2">
          {filteredRoutes.map((route) => (
            <div
              key={route.path}
              className="flex items-center justify-between p-3 border rounded-lg hover:bg-muted/50 transition-colors group"
            >
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1 flex-wrap">
                  <span className="font-mono text-sm truncate font-medium">{route.path}</span>
                  <RouteStatusBadge status={route.status} source={route.source} />
                  
                  {route.hasWarnings && (
                    <Badge variant="destructive" className="text-xs">
                      <AlertTriangle className="h-3 w-3 mr-1" />
                      Warnings
                    </Badge>
                  )}
                  
                  <Badge variant="outline" className="text-xs">
                    {route.category}
                  </Badge>
                  
                  <Badge variant="secondary" className="text-xs">
                    P: {route.priority.toFixed(1)}
                  </Badge>
                </div>
                
                {route.title ? (
                  <p className="text-sm text-muted-foreground truncate">{route.title}</p>
                ) : (
                  <p className="text-sm text-muted-foreground italic">Sin título definido</p>
                )}
              </div>
              
              <div className="flex gap-2 ml-4">
                {route.status === 'optimized' && (
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={() => onEditPage(route.path)}
                    title="Editar SEO"
                  >
                    <Edit className="h-4 w-4" />
                  </Button>
                )}
                
                {(route.status === 'auto-generated' || route.status === 'no-data') && (
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={() => onEditPage(route.path)}
                    title="Optimizar SEO"
                    className="opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    <Sparkles className="h-4 w-4 text-blue-500" />
                  </Button>
                )}
              </div>
            </div>
          ))}
          
          {filteredRoutes.length === 0 && (
            <div className="text-center py-12 text-muted-foreground">
              <Search className="h-12 w-12 mx-auto mb-4 opacity-20" />
              <p>No se encontraron rutas con los filtros aplicados</p>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
};
