project_id = "pmldrjkmkjwbvaudjjye"

[functions.generate-seo-suggestions]
verify_jwt = true

[functions.webhook-handler]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.get-user-orders]
verify_jwt = true

[functions.gsc-data]
verify_jwt = true

[functions.indexnow-proxy]
verify_jwt = false

[functions.translate-seo]
verify_jwt = true